// Generated by scripts/build-malecns.mjs from official v1.0 files.
export const CNS={"id":"male-cns:v1.0","neuronCount":167122,"edgeCount":6241236,"displayCount":28195,"license":"CC BY 4.0"} as const;
