import {CNS} from './cnsDataset.ts';
import { candidates } from './experiment.ts';
export type FlightMode='baseline'|'disconnected'|'silenced';
export type FlightFrame={time:number;position:[number,number,number];velocity:[number,number,number];heading:number;activity:number[]|Float32Array;output:number[];sensory:number[];focus:number;action:string;visits:number;mode:string;neuronCount:number;edgeCount:number;spikeCount:number;activeNeuronCount:number;traversedEdges:number;computeMs:number;tick:number;ready:boolean;error?:string;dynamicsLabel:string;fireState:Uint8Array;displayedNeuronCount:number;compactDisplay?:boolean;motorRates:number[];spikeBits?:Uint8Array;groupSpikeCounts?:Uint32Array};
type Reply=Record<string,any>;
// One shared graph download per page; each worker receives its own copy (postMessage transfers the buffer). Twenty workers must not fetch the 27 MB connectome twenty times.
let graphCache:Promise<{buffer:ArrayBuffer;ids:string[]}>|null=null;
function loadGraph(){if(!graphCache)graphCache=Promise.all([fetch('/data/malecns/connectome.bin.gz',{signal:AbortSignal.timeout(90000)}).then(r=>{if(!r.ok)throw Error('Graph fetch failed');return r.arrayBuffer();}),fetch('/data/malecns/root-ids.json',{signal:AbortSignal.timeout(90000)}).then(r=>r.json())]).then(([buffer,ids])=>({buffer,ids})).catch(e=>{graphCache=null;throw e;});return graphCache.then(g=>({buffer:g.buffer.slice(0),ids:g.ids}));}
export class FlightExperiment {
 private worker:Worker|null=null; private seed:number;private busy=false;private generation=0;private serial=0;private pending=new Map<number,{resolve:(r:Reply)=>void,reject:(e:Error)=>void}>();private listeners=new Set<(frame:FlightFrame)=>void>();private initPromise:Promise<void>|null=null;
 private lastCandidate=-1;private p:[number,number,number]=[-2,1.4,.5];private v:[number,number,number]=[0,0,0];private time=0;private visits=0;private bearing=.65;
 rootIds:string[]=[];originalToSorted=new Uint32Array();sortedToOriginal=new Uint32Array();
 private frame:FlightFrame=this.empty();
 constructor(seed=2026){this.seed=seed;}
 private empty():FlightFrame{return {time:0,position:[-2,1.4,.5],velocity:[0,0,0],heading:0,activity:[],output:[0,0,0],sensory:[],focus:0,action:'LOADING FULL CONNECTOME',visits:0,mode:'baseline',neuronCount:0,edgeCount:0,spikeCount:0,activeNeuronCount:0,traversedEdges:0,computeMs:0,tick:0,ready:false,dynamicsLabel:'Full MaleCNS brain + VNC LIF loading',fireState:new Uint8Array(),displayedNeuronCount:CNS.displayCount,motorRates:[]};}
 private request(type:string,payload:Reply={}):Promise<Reply>{return new Promise((resolve,reject)=>{if(!this.worker){reject(Error('Worker unavailable'));return;}const id=++this.serial;const timeout=setTimeout(()=>{this.pending.delete(id);reject(Error(type==='init'?'Brain initialization timed out. Restart with fewer brains.':'The neural worker stopped responding. Restart the simulation.'));},type==='init'?45000:15000);this.pending.set(id,{resolve:r=>{clearTimeout(timeout);resolve(r);},reject:e=>{clearTimeout(timeout);reject(e);}});this.worker.postMessage({type,id,...payload},payload.buffer instanceof ArrayBuffer?[payload.buffer]:[]);});}
 init():Promise<void>{if(this.initPromise)return this.initPromise;this.initPromise=(async()=>{this.worker=new Worker('/engine/malecns/worker.js',{type:'module'});this.worker.onmessage=({data:r})=>{const p=this.pending.get(r.id);if(!p)return;this.pending.delete(r.id);r.type==='error'?p.reject(Error(r.message)):p.resolve(r);};this.worker.onerror=(e)=>{for(const p of this.pending.values())p.reject(Error(e.message));this.pending.clear();};const {buffer,ids}=await loadGraph();this.rootIds=ids;const info=await this.request('init',{buffer,rootIds:ids,seed:this.seed});this.originalToSorted=info.originalToSorted;this.sortedToOriginal=info.sortedToOriginal;this.frame={...this.frame,ready:true,neuronCount:info.neuronCount,edgeCount:info.edgeCount,dynamicsLabel:info.dynamicsLabel,action:'FULL CONNECTOME READY'};})().catch(e=>{this.frame={...this.frame,error:String(e),action:'FULL ENGINE ERROR'};throw e;});return this.initPromise;}
 subscribe(fn:(f:FlightFrame)=>void){this.listeners.add(fn);return ()=>{this.listeners.delete(fn);};}
 reset(seed=2026){this.seed=seed;this.generation++;this.p=[-2,1.4,.5];this.v=[0,0,0];this.bearing=.65;this.time=0;this.visits=0;this.lastCandidate=-1;const old=this.frame;this.frame={...this.empty(),ready:old.ready,neuronCount:old.neuronCount,edgeCount:old.edgeCount,dynamicsLabel:old.dynamicsLabel,action:old.ready?'RESET / NO DRIVE':'LOADING FULL CONNECTOME'};if(this.worker)void this.request('reset',{seed}).catch(()=>{});}
 step(dt:number,candidate:number,target:number,mode:FlightMode):FlightFrame{if(!this.busy)void this.stepAsync(dt,candidate,target,mode).catch(e=>{this.frame={...this.frame,error:String(e),action:'FULL ENGINE ERROR'};});return this.frame;}
 async stepAsync(dtSeconds:number,candidateIndex:number,targetIndex:number,mode:FlightMode):Promise<FlightFrame>{if(this.busy)return this.frame;this.busy=true;const generation=this.generation;try{await this.init();if(generation!==this.generation)return this.frame;const dt=Math.min(.1,Math.max(.001,Number.isFinite(dtSeconds)?dtSeconds:.05));const ci=Math.max(0,Math.min(7,Math.floor(candidateIndex)));const c=candidates(this.seed)[ci];const a=ci*Math.PI/4,relative=[Math.cos(a)*1.8-this.p[0],1.35+(targetIndex%3)*.3-this.p[1],Math.sin(a)*1.8-this.p[2]];const clamp=(x:number)=>Math.max(0,Math.min(1,x));const sensory=[clamp(.5+relative[0]/7),clamp(.5+relative[2]/7),clamp(.5+relative[1]/3),clamp(Math.hypot(...relative)/6),c.features[0],c.features[3],clamp(Math.hypot(...this.v)/2),c.features[6]];
 const r=await this.request('step',{sensory,mode,compact:true});if(generation!==this.generation)return this.frame;const output=r.output as number[];
 // Authored vehicle decoder: differential spikes turn heading; forward spikes supply thrust.
 // No direct sensory-to-force path. Reflect bearing at passive walls to avoid a stationary wall-pushing artifact.
 this.bearing+=output[0]*dt*2.5;
 const force=[Math.sin(this.bearing)*output[2]*8,output[1]*5,Math.cos(this.bearing)*output[2]*8];
 for(let i=0;i<3;i++){this.v[i]=(this.v[i]+force[i]*dt)*Math.exp(-1.5*dt);this.p[i]+=this.v[i]*dt;const lo=i===1?.6:-2.6,hi=i===1?2.8:2.6;if(this.p[i]<lo||this.p[i]>hi){this.p[i]=Math.max(lo,Math.min(hi,this.p[i]));this.v[i]*=-.8;if(i===0)this.bearing=-this.bearing;if(i===2)this.bearing=Math.PI-this.bearing;}}
 this.time+=dt;if(this.lastCandidate!==ci){this.visits++;this.lastCandidate=ci;}const drive=Math.hypot(...output);this.frame={...this.frame,...r,time:this.time,position:[...this.p],velocity:[...this.v],heading:this.bearing,activity:r.activity,output,sensory,focus:clamp(drive),action:mode==='disconnected'?'SYNAPSES DISCONNECTED':mode==='silenced'?'ELECTRICAL SILENCE':drive<1e-5?'PROPAGATING / NO MOTOR SPIKES':'DESCENDING NEURAL DRIVE',visits:this.visits,mode,ready:true};for(const fn of this.listeners)fn(this.frame);return this.frame;}finally{this.busy=false;}}
 async inspectAsync(sensory:number[],mode:FlightMode='baseline',record=true):Promise<FlightFrame>{if(this.busy)throw Error('Overlapping inspection step');this.busy=true;try{await this.init();const input=Array.from({length:9},(_,i)=>Math.max(0,Math.min(1,Number(sensory[i])||0)));const r=await this.request('step',{sensory:input,mode,compact:true,record});this.time+=.05;this.frame={...this.frame,...r,time:this.time,sensory:input,output:r.output,mode,ready:true,position:[0,0,0],velocity:[0,0,0],action:'CHEMICAL DESCRIPTOR REVIEW'};return this.frame;}finally{this.busy=false;}}
 dispose(){this.generation++;this.worker?.terminate();this.worker=null;for(const p of this.pending.values())p.reject(Error('Disposed'));this.pending.clear();this.listeners.clear();}
}
