import {zipSync,strToU8} from 'fflate';
export type SavedNeuralRecord={projectPath:string;url:string;bytes:number;runId:string};
export type Sample={fly:number;compoundId:string;tick:number;spikeCount:number;time:number;sensory:number[];mode:string;position?:number[];velocity?:number[];destination?:number;feeding?:number;learned?:number[];bits:Uint8Array};
function request<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
/** User policy (2026-09-15): only the live session's recordings are kept in the browser. Called once at session start,
 * BEFORE this session creates its first run, so the whole database can simply be dropped. If another tab still holds the
 * database open (deleteDatabase reports "blocked"), fall back to per-run range deletes in the background without reading data. */
export async function pruneOtherSessions(keepSession:string):Promise<{mode:'dropped'|'ranges'|'nothing';runs:number}>{
 const open=()=>{const r=indexedDB.open('fddd-neural-assays',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('chunks'))r.result.createObjectStore('chunks',{keyPath:'key'});if(!r.result.objectStoreNames.contains('runs'))r.result.createObjectStore('runs',{keyPath:'id'});};return request(r);};
 let db=await open();let runs:{id:string;metadata?:{colonySession?:string}}[];try{runs=await request(db.transaction('runs').objectStore('runs').getAll()) as typeof runs;}finally{db.close();}
 const others=runs.filter(x=>x.metadata?.colonySession!==keepSession);if(!others.length)return {mode:'nothing',runs:0};
 if(others.length===runs.length){
  const dropped=await new Promise<boolean>(resolve=>{const d=indexedDB.deleteDatabase('fddd-neural-assays');let settled=false;const done=(v:boolean)=>{if(!settled){settled=true;resolve(v);}};d.onsuccess=()=>done(true);d.onerror=()=>done(false);d.onblocked=()=>done(false);setTimeout(()=>done(false),4000);});
  if(dropped)return {mode:'dropped',runs:others.length};
 }
 // Background fallback: range deletes only, no data reads, one run per transaction so the UI stays responsive.
 void (async()=>{const db2=await open();try{for(const run of others){const tx=db2.transaction(['chunks','runs'],'readwrite');tx.objectStore('chunks').delete(IDBKeyRange.bound([run.id,0],[run.id,Number.MAX_SAFE_INTEGER]));tx.objectStore('runs').delete(run.id);await new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});await new Promise(r=>setTimeout(r,20));}}catch(e){console.warn('[fddd] background prune stopped',e);}finally{db2.close();}})();
 return {mode:'ranges',runs:others.length};
}
export class NeuralRecord{readonly id='assay-'+Date.now()+'-'+Math.random().toString(36).slice(2,6);private db!:IDBDatabase;steps=0;bytes=0;sequence=0;
 async init(metadata:Record<string,unknown>={}){const r=indexedDB.open('fddd-neural-assays',2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('chunks'))r.result.createObjectStore('chunks',{keyPath:'key'});if(!r.result.objectStoreNames.contains('runs'))r.result.createObjectStore('runs',{keyPath:'id'});};this.db=await request(r);await request(this.db.transaction('runs','readwrite').objectStore('runs').put({id:this.id,createdAt:new Date().toISOString(),metadata}));}
 async append(samples:Sample[]){const rows=samples.map(({bits,...meta})=>({...meta,byteLength:bits.length}));const tx=this.db.transaction('chunks','readwrite');const done=new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??Error('Recording aborted'));});tx.objectStore('chunks').put({key:[this.id,this.sequence++],rows,bits:samples.map(s=>new Blob([s.bits.slice().buffer as ArrayBuffer]))});await done;this.steps+=samples.length;this.bytes+=samples.reduce((a,s)=>a+s.bits.length,0);}
 async export(manifest:Record<string,unknown>,rootIds:string[],sortedToOriginal:Uint32Array){const chunks=await request(this.db.transaction('chunks').objectStore('chunks').getAll(IDBKeyRange.bound([this.id,0],[this.id,Number.MAX_SAFE_INTEGER])));const parts:Uint8Array[][]=[],offsets:number[]=[],rows:Record<string,unknown>[]=[];for(const chunk of chunks)for(let j=0;j<chunk.rows.length;j++){const r=chunk.rows[j],bits=new Uint8Array(await chunk.bits[j].arrayBuffer());while(parts.length<=r.fly){parts.push([]);offsets.push(0);}rows.push({...r,byteOffset:offsets[r.fly],file:`brain-${r.fly+1}.spikes.bin`});offsets[r.fly]+=bits.length;parts[r.fly].push(bits);}const files:Record<string,Uint8Array>={'manifest.json':strToU8(JSON.stringify({...manifest,runId:this.id,encoding:`LSB-first bitset, sorted-engine neuron index,${rootIds.length} valid bits per frame; trailing bits zero`,recorded:'Every computed neuron spike flag at every inspection step. Membrane potentials are NOT retained.',storedNeuronCount:rootIds.length,brainFiles:parts.length,steps:this.steps},null,2)),'frames.jsonl':strToU8(rows.map(r=>JSON.stringify(r)).join('\n')),'root-ids.json':strToU8(JSON.stringify(rootIds)),'sorted-to-original.json':strToU8(JSON.stringify(Array.from(sortedToOriginal)))};parts.forEach((p,i)=>{const a=new Uint8Array(offsets[i]);let at=0;for(const b of p){a.set(b,at);at+=b.length;}files[`brain-${i+1}.spikes.bin`]=a;});const zip=zipSync(files,{level:3});const blob=new Blob([zip.buffer as ArrayBuffer],{type:'application/zip'});try{const response=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/zip'},body:blob,redirect:'error',signal:AbortSignal.timeout(120000)});if(!response.ok)throw Error(`Project recording server rejected save (HTTP ${response.status}).`);const saved=await response.json();if(typeof saved.url!=='string'||!/^\/data\/records\/[A-Za-z0-9_-]+\.zip$/.test(saved.url)||saved.bytes!==zip.byteLength)throw Error('Project recording server returned an invalid save confirmation.');return {projectPath:'public'+saved.url,url:saved.url,bytes:saved.bytes,runId:this.id} satisfies SavedNeuralRecord;}catch(e){throw Error('Project save failed. All recorded chunks remain in IndexedDB; no browser download was started. Keep this page and retry with the local project server available. '+String(e));}}
 close(){this.db?.close();}
}
