export type RewardModel={schemaVersion:string;mechanism:string;featureCount:number;mean:number[];scale:number[];weights:number[];bias:number;rewardReferenceScores:number[];[key:string]:unknown};
export const NEURAL_ENCODING_VERSION='canonical-smiles-token-v1';
export function chemicalFeatures(smiles:string):number[]{const tokens=smiles.match(/Cl|Br|\[[^\]]+\]|[A-Za-z]|[0-9]|[^\s]/g)??[];const out=new Array<number>(128).fill(0);for(let n=1;n<=3;n++)for(let i=0;i+n<=tokens.length;i++){let h=2166136261;for(const ch of tokens.slice(i,i+n).join(''))h=Math.imul(h^ch.charCodeAt(0),16777619);out[(h>>>0)%128]=1;}return out;}
// Authored sensory encoding of chemical representation, never score/reward. Not a fly chemoreceptor model.
export function chemicalSensory(smiles:string,phase=0):number[]{const f=chemicalFeatures(smiles),count=(r:RegExp)=>(smiles.match(r)||[]).length,clip=(v:number)=>Math.max(0,Math.min(1,v));const channels=[clip(smiles.length/150),clip(count(/C|c/g)/40),clip(count(/N|n/g)/10),clip(count(/O|o/g)/10),clip(count(/c|n|o|s/g)/35),clip(count(/[0-9]/g)/16),clip(count(/Cl|Br|F|I/g)/6),clip(count(/\(/g)/14)];return channels.map((v,i)=>{let hash=0;for(let j=0;j<4;j++)hash+=f[(phase*32+i*4+j)%128];return clip(v*.75+hash/4*.25);});}
export function predictFeeding(model:RewardModel,features:ArrayLike<number>):number{if(features.length!==model.featureCount)throw Error('Neural feature schema mismatch');let z=model.bias;for(let i=0;i<features.length;i++)z+=model.weights[i]*(features[i]-model.mean[i])/model.scale[i];return 1/(1+Math.exp(-Math.max(-30,Math.min(30,z))));}
export function rewardForScore(score:number,trainScores:number[]):number{if(!trainScores.length)throw Error('Training reward reference is empty');let better=0,ties=0;for(const s of trainScores){if(s>score)better++;else if(s===score)ties++;}return (better+.5*ties)/trainScores.length;}
export function rankCorrelation(a:number[],b:number[]):number{if(a.length!==b.length||a.length<2)return 0;const rank=(xs:number[])=>xs.map(v=>{let lower=0,equal=0;for(const x of xs){if(x<v)lower++;else if(x===v)equal++;}return lower+(equal-1)/2;});const x=rank(a),y=rank(b),mx=x.reduce((s,v)=>s+v,0)/x.length,my=y.reduce((s,v)=>s+v,0)/y.length;let xy=0,xx=0,yy=0;for(let i=0;i<x.length;i++){xy+=(x[i]-mx)*(y[i]-my);xx+=(x[i]-mx)**2;yy+=(y[i]-my)**2;}return xx&&yy?xy/Math.sqrt(xx*yy):0;}

export const NEURAL_STEPS=16;
export function aggregateCircuitFeatures(steps:Array<{groupSpikeCounts:ArrayLike<number>;motorRates:number[]}>,groupSizes:number[]):number[]{if(steps.length!==NEURAL_STEPS)throw Error('Expected16 actual circuit steps');const out:number[]=[];for(let p=0;p<4;p++){for(let g=0;g<groupSizes.length;g++){let sum=0;for(let t=p*4;t<p*4+4;t++)sum+=steps[t].groupSpikeCounts[g]/Math.max(1,groupSizes[g]);out.push(sum/4);}for(let m=0;m<6;m++){let sum=0;for(let t=p*4;t<p*4+4;t++)sum+=steps[t].motorRates[m];out.push(sum/4);}}return out;}
