import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Worker} from 'node:worker_threads';

test('actual full FlyWire worker: identity, propagation, controls, reset and measured runtime',async()=>{
 const worker=new Worker(new URL('./flywire-worker-harness.mjs',import.meta.url));let id=0;const pending=new Map<number,{resolve:(v:any)=>void,reject:(e:Error)=>void}>();worker.on('message',m=>{const p=pending.get(m.id);pending.delete(m.id);if(m.type==='error')p?.reject(Error(m.message));else p?.resolve(m);});const call=(type:string,data:Record<string,unknown>={})=>new Promise<any>((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});worker.postMessage({type,id:n,...data});});
 try{const bytes=fs.readFileSync(new URL('../public/data/flywire/connectome.bin.gz',import.meta.url));const ids=JSON.parse(fs.readFileSync(new URL('../public/data/flywire/root-ids.json',import.meta.url),'utf8'));const t=performance.now();const ready=await call('init',{buffer:bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length),rootIds:ids});assert.equal(ready.neuronCount,139255);assert.equal(ready.edgeCount,2698236);assert.equal(new Set(ids).size,139255);for(let i=0;i<139255;i++)assert.equal(ready.sortedToOriginal[ready.originalToSorted[i]],i);
 const initMs=performance.now()-t,sensory=[.7,.5,.5,.4,.8,.3,.2,.6];let first:any,last:any,maxDrive=0,maxEdges=0;const times:number[]=[];let p=[-2,1.4,.5],v=[0,0,0];for(let i=0;i<120;i++){last=await call('step',{sensory,mode:'baseline'});if(!i)first=last;assert.equal(last.activity.length,139255);assert.equal(last.activeNeuronCount,139255);assert.equal(last.groupSpikeCounts.constructor.name,'Uint32Array');assert.equal(last.groupSpikeCounts.reduce((a:number,b:number)=>a+b,0),last.spikeCount);assert.ok(last.output.every(Number.isFinite));maxDrive=Math.max(maxDrive,Math.hypot(...last.output));maxEdges=Math.max(maxEdges,last.traversedEdges);if(i>=20)times.push(last.computeMs);for(let k=0;k<3;k++){v[k]=(v[k]+last.output[k]*3*.05)*Math.exp(-1.5*.05);p[k]+=v[k]*.05;}}
 assert.ok(maxDrive>.1,'visible downstream neural output');assert.ok(maxEdges>100000);assert.ok(Math.hypot(p[0]+2,p[1]-1.4,p[2]-.5)>.1,'neural drive causes visible motion');await call('reset');const repeated=await call('step',{sensory,mode:'baseline'});assert.equal(repeated.tick,1);assert.deepEqual(repeated.fireState,first.fireState);assert.deepEqual(repeated.output,first.output);
 for(const mode of ['disconnected','silenced']){await call('reset');for(let i=0;i<40;i++){const f=await call('step',{sensory,mode});assert.deepEqual(f.output,[0,0,0]);assert.equal(f.traversedEdges,0);if(mode==='silenced')assert.equal(f.spikeCount,0);}}
 // No autonomous ticking: a pause is verified by a stable next sequence number.
 const prior=await call('step',{sensory,mode:'silenced'});await new Promise(r=>setTimeout(r,100));const after=await call('step',{sensory,mode:'silenced'});assert.equal(after.tick,prior.tick+1);
 times.sort((a,b)=>a-b);console.log(JSON.stringify({engine:'actual-worker-full-FAFB',initMs,neurons:ready.neuronCount,edges:ready.edgeCount,meanMs:times.reduce((a,b)=>a+b,0)/times.length,p95Ms:times[95],maxMs:times[99],maxDrive,maxTraversedEdges:maxEdges,finalSpikeCount:last.spikeCount,displacement:Math.hypot(p[0]+2,p[1]-1.4,p[2]-.5)}));
 }finally{await worker.terminate();}
});
