import {CNS} from '../lib/cnsDataset.ts';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import type {FlightFrame} from '../lib/flight';
import {REGIONS,regionOfGroup} from './brainRegions';
/** Measured MaleCNS v1.0 soma/tosoma sample coordinates. Points are coloured by their official superclass region (viewing palette); brightness is real membrane activity and flashes are real spikes of this fly's computation. */
export function FlyWireBrainScene({frame,className,compact=false,tone=1}:{frame?:FlightFrame;className?:string;compact?:boolean;tone?:number}){
 const host=useRef<HTMLDivElement>(null),latest=useRef(frame);const [label,setLabel]=useState('Loading MaleCNS brain + VNC soma coordinates');useEffect(()=>{latest.current=frame;},[frame]);
 useEffect(()=>{const el=host.current!;let disposed=false,raf=0,lastPaint=0,lastTick=-1;const abort=new AbortController();let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{setLabel('WebGL unavailable; circuit computation remains independent');return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(39,1,.1,100);camera.position.set(3.9,2.8,5.4);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=13;controls.autoRotate=false;const group=new THREE.Group();scene.add(group);let geometry:THREE.BufferGeometry|undefined,material:THREE.ShaderMaterial|undefined;let indices:number[]=[];let glow=new Float32Array(),region=new Uint8Array();
 const render=()=>{if(!geometry||!material)return;const colors=geometry.getAttribute('color'),sizes=geometry.getAttribute('strength'),f=latest.current,newTick=!!f&&f.tick!==lastTick;if(newTick)group.rotation.y=Math.sin((f?.tick??0)*.002+tone*.5)*.12;for(let i=0;i<indices.length;i++){const k=f?.compactDisplay?i:indices[i],a=Math.max(0,Math.min(1,f?.activity[k]||0));glow[i]*=.70;if(newTick&&f?.fireState[k])glow[i]=1;const flash=glow[i],l=.12+.60*a,base=REGIONS[region[i]].color;colors.setXYZ(i,base[0]*l*(1-flash)+flash*(.35+.65*base[0]),base[1]*l*(1-flash)+flash*(.35+.65*base[1]),base[2]*l*(1-flash)+flash*(.35+.65*base[2]));sizes.setX(i,.45+a*.5+flash*.95);}if(f)lastTick=f.tick;colors.needsUpdate=true;sizes.needsUpdate=true;controls.update();renderer.render(scene,camera);};
 const animate=(now:number)=>{if(now-lastPaint>40){render();lastPaint=now;}raf=requestAnimationFrame(animate);};raf=requestAnimationFrame(animate);const fit=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(1,el.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(material)material.uniforms.pixelRatio.value=renderer.getPixelRatio();render();};const observer=new ResizeObserver(fit);observer.observe(el);
 fetch('/data/malecns/display-points.json',{signal:abort.signal}).then(r=>r.json()).then(data=>{if(disposed)return;const points=data.points as {position:number[];sortedIndex:number;group:string}[];const bounds=[0,1,2].map(k=>{const v=points.map(p=>p.position[k]).sort((a,b)=>a-b);return [v[Math.floor(v.length*.005)],v[Math.floor(v.length*.995)]];});const scale=4.8/Math.max(...bounds.map(b=>b[1]-b[0]));const positions=new Float32Array(points.length*3),colors=new Float32Array(points.length*3),strength=new Float32Array(points.length);glow=new Float32Array(points.length);region=new Uint8Array(points.length);points.forEach((p,i)=>{indices.push(p.sortedIndex);positions[i*3]=(p.position[0]-(bounds[0][1]+bounds[0][0])/2)*scale;positions[i*3+1]=-(p.position[1]-(bounds[1][1]+bounds[1][0])/2)*scale;positions[i*3+2]=(p.position[2]-(bounds[2][1]+bounds[2][0])/2)*scale;region[i]=regionOfGroup(p.group);});geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));geometry.setAttribute('strength',new THREE.BufferAttribute(strength,1));material=new THREE.ShaderMaterial({uniforms:{pixelRatio:{value:renderer.getPixelRatio()}},vertexShader:'attribute vec3 color; attribute float strength; varying vec3 c; uniform float pixelRatio; void main(){c=color;vec4 p=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*p;gl_PointSize=clamp((.75+strength*.65)*pixelRatio*7.0/-p.z,1.0,6.0);}',fragmentShader:'varying vec3 c;void main(){float d=length(gl_PointCoord-vec2(.5));if(d>.5)discard;float a=pow(1.0-d*2.0,1.4);gl_FragColor=vec4(c,a*.86);}',transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});group.add(new THREE.Points(geometry,material));setLabel(`${CNS.displayCount.toLocaleString()} measured soma samples / ${CNS.neuronCount.toLocaleString()} CNS neurons computed; brain + VNC. Actual spike flashes.`);fit();}).catch(e=>{if(!disposed)setLabel('Coordinate display unavailable: '+String(e));});
 return()=>{disposed=true;cancelAnimationFrame(raf);abort.abort();observer.disconnect();controls.dispose();geometry?.dispose();material?.dispose();renderer.dispose();renderer.domElement.remove();};},[]);
 return <div className={className} title={label} style={{position:'relative',width:'100%',height:'100%',minHeight:compact?105:260}}><div ref={host} style={{position:'absolute',inset:0}}/>{!compact&&<small style={{position:'absolute',bottom:8,left:10,right:10,fontSize:10,color:'#87aaa8',pointerEvents:'none'}}>{label}</small>}</div>;
}
