import fs from 'node:fs';const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('public/engine/malecns/core.js',s=>s.replace('initEngine(buffer, ids)','initEngine(buffer, ids, config)').replace("n!==139255||e!==2698236",'n!==config.neuronCount||e!==config.edgeCount').replace('Full FAFB graph/identity mismatch','MaleCNS v1.0 graph/identity mismatch').replace('[0,6,7,10,11].includes(groupId[i])','config.sensoryGroups.includes(groupId[i])').replace('groupId[i]===35','config.motorGroups.includes(groupId[i])').replace('engineered encoder/descending decoder','MaleCNS sensory encoder / annotated CNS motor decoder'));
edit('public/engine/malecns/worker.js',s=>s.replaceAll('/data/flywire/','/data/malecns/').replace('await initEngine(m.buffer,ids)',"await initEngine(m.buffer,ids,await fetch('/data/malecns/manifest.json').then(r=>r.json()))"));
edit('src/lib/flight.ts',s=>"import {CNS} from './cnsDataset.ts';\n"+s.replaceAll('/engine/flywire/','/engine/malecns/').replaceAll('/data/flywire/','/data/malecns/').replace('Full FlyWire LIF loading','Full MaleCNS brain + VNC LIF loading').replace('displayedNeuronCount:19894','displayedNeuronCount:CNS.displayCount').replace("this.request('init',{buffer})","this.request('init',{buffer,rootIds:ids})"));
edit('src/lib/colonyPolicy.ts',s=>"import {CNS} from './cnsDataset.ts';\n"+s.replace('Math.ceil(139255/8)','Math.ceil(CNS.neuronCount/8)'));
edit('src/lib/useContinuousColony.ts',s=>"import {CNS} from './cnsDataset.ts';\n"+s.replace('neuronCount:139255,edgeCount:2698236','dataset:CNS.id,neuronCount:CNS.neuronCount,edgeCount:CNS.edgeCount').replace('Full 139255-neuron spike bitset absent','Full MaleCNS neuron spike bitset absent').replace('frame.neuronCount!==139255||frame.edgeCount!==2698236','frame.neuronCount!==CNS.neuronCount||frame.edgeCount!==CNS.edgeCount').replace("license:'FlyWire CC BY-NC 4.0; noncommercial'","license:CNS.license"));
edit('src/lib/neuralRecord.ts',s=>s.replace("'LSB-first bitset, sorted-engine neuron index,139255 valid bits per frame; trailing bits zero'","`LSB-first bitset, sorted-engine neuron index,${rootIds.length} valid bits per frame; trailing bits zero`").replace('storedNeuronCount:139255','storedNeuronCount:rootIds.length'));
edit('src/components/FlyWireBrainScene.tsx',s=>"import {CNS} from '../lib/cnsDataset.ts';\n"+s.replaceAll('/data/flywire/','/data/malecns/').replaceAll('measured FAFB','MaleCNS brain + VNC soma').replace("'19,894 anatomical samples / 139,255 computed. Spatial green/gold palette; actual spike flashes. Camera framing may clip extreme coordinates.'","`${CNS.displayCount.toLocaleString()} measured soma samples / ${CNS.neuronCount.toLocaleString()} CNS neurons computed; brain + VNC. Actual spike flashes.`").replace("const scale=5.4/(bounds[0][1]-bounds[0][0]);","const scale=4.8/Math.max(...bounds.map(b=>b[1]-b[0]));"));
edit('src/main.tsx',s=>"import {CNS} from './lib/cnsDataset.ts';\n"+s.replace('4 × 139,255','4 × {CNS.neuronCount.toLocaleString()}').replace('neurons · independent full graphs','neurons · MaleCNS brain + VNC').replace('19,894 anatomical display samples / 139,255 computed per fly','{CNS.displayCount.toLocaleString()} measured soma samples / {CNS.neuronCount.toLocaleString()} CNS neurons per fly').replace('Four independent full FlyWire FAFB circuits','Four independent MaleCNS v1.0 brain + VNC circuits').replace('all 139,255 spike flags','all {CNS.neuronCount.toLocaleString()} spike flags').replace('Current runtime is the female FlyWire brain, not brain plus VNC.','Current runtime is the connected male brain plus VNC.').replace('It requires its own full backend and is not silently appended to female FAFB.','The runtime uses its own v1.0 neuron IDs, connectivity, neurotransmitter predictions and measured soma coordinates. No female FAFB neurons are appended. Edges with fewer than five synapses are excluded; dynamics and sensory/motor decoding remain authored models.').replace('/data/flywire/NOTICE.md','/data/malecns/NOTICE.md').replace('Full FlyWire runtime · noncommercial research demonstration','MaleCNS v1.0 runtime · CC BY 4.0 connectivity · research demonstration'));
