import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),project=path.resolve(here,'../..');const at=process.argv.indexOf('--cache');const cache=at>=0?process.argv[at+1]:path.join(here,'cache');const out=path.join(project,'public/data/learning');fs.mkdirSync(out,{recursive:true});
const seed=20260914;const digest=(v,algo='sha256')=>crypto.createHash(algo).update(v).digest('hex');const rank=s=>digest(seed+':'+s);const expected={'dockstring-dataset.tsv':'d0553abd8563bfbbe862eb1d7ec6be6d','cluster_split.tsv':'46660336fbc138d5429c3137f081a423'};const text={};const hashes={};for(const [name,md5] of Object.entries(expected)){const b=fs.readFileSync(path.join(cache,name));if(digest(b,'md5')!==md5)throw Error('Official Figshare MD5 mismatch for '+name);text[name]=b.toString('utf8');hashes[name]={md5,sha256:digest(b),bytes:b.length};}
const clusterRows=text['cluster_split.tsv'].trim().split('\n').slice(1).map(l=>l.split('\t'));const clusters=new Map(clusterRows.map(r=>[r[0],{smiles:r[1],cluster:r[2],originalSplit:r[3]}]));const scoreLines=text['dockstring-dataset.tsv'].trim().split('\n'),head=scoreLines.shift().split('\t');const col=head.indexOf('PARP1');if(col<0)throw Error('PARP1 missing');
const all=scoreLines.map((line,i)=>{const r=line.split('\t'),c=clusters.get(r[0]);if(!c||c.smiles!==r[1])throw Error('Identity/split join mismatch at '+r[0]);return {id:r[0],inchikey:r[0],smiles:r[1],score:Number(r[col]),cluster:c.cluster,originalSplit:c.originalSplit,sourceRow:i+2};}).filter(r=>Number.isFinite(r.score));
// Keep a deterministic single representative per connectivity layer (stricter than exact identity).
const unique=new Map();for(const r of [...all].sort((a,b)=>rank('identity:'+a.id).localeCompare(rank('identity:'+b.id))))if(!unique.has(r.inchikey.split('-')[0]))unique.set(r.inchikey.split('-')[0],r);const rows=[...unique.values()];
// Original official cluster-held-out TEST remains untouched. Validation is entire original TRAIN clusters.
for(const r of rows)r.split=r.originalSplit==='test'?'test':parseInt(rank('validation-cluster:'+r.cluster).slice(0,8),16)%5===0?'validation':'train';
// Quantile boundaries are learned only from the final training pool, never from held-out scores.
const trainScores=rows.filter(r=>r.split==='train').map(r=>r.score).sort((a,b)=>a-b);const boundaries=Array.from({length:9},(_,i)=>trainScores[Math.floor(trainScores.length*(i+1)/10)]);const bin=s=>boundaries.findIndex(b=>s<=b)<0?9:boundaries.findIndex(b=>s<=b);for(const r of rows)r.scoreBin=bin(r.score);
const selected=[];const counts={train:1600,validation:400,test:400};for(const [split,n] of Object.entries(counts))for(let b=0;b<10;b++){const pool=rows.filter(r=>r.split===split&&r.scoreBin===b).sort((a,c)=>rank('sample:'+a.id).localeCompare(rank('sample:'+c.id)));if(pool.length<n/10)throw Error('Insufficient score-bin population; do not silently change protocol');selected.push(...pool.slice(0,n/10));}
selected.sort((a,b)=>rank('presentation:'+a.id).localeCompare(rank('presentation:'+b.id)));const used=new Map(),connectivity=new Set();for(const r of selected){const previous=used.get(r.cluster);if(previous&&previous!==r.split)throw Error('Cluster leakage');used.set(r.cluster,r.split);const key=r.inchikey.split('-')[0];if(connectivity.has(key))throw Error('Duplicate connectivity');connectivity.add(key);}
const source={name:'DOCKSTRING PARP1',url:'https://figshare.com/articles/dataset/dockstring_dataset/16511577',doi:'10.6084/m9.figshare.16511577.v1',paperDoi:'10.1021/acs.jcim.1c01334',version:1,targetProtocolNote:'DOCKSTRING published PARP1 scores use a distinct protocol from the separately executed Webina/PDB4R6E four-compound demo; do not pool their scores or imply common calibration.',license:'Apache-2.0 (Figshare release metadata)',licenseUrl:'https://www.apache.org/licenses/LICENSE-2.0.html',scoresUrl:'https://ndownloader.figshare.com/files/35948138',clusterSplitUrl:'https://ndownloader.figshare.com/files/35948123',hashes};
const data={schemaVersion:'fddd-dockstring-learning-v1',source,target:'PARP1',scoreType:'AutoDock Vina docking score; not measured affinity',units:'kcal/mol',rankingDirection:'lower-is-more-favorable',sampling:{seed,total:2400,splitCounts:counts,sourceRows:all.length,uniqueConnectivityRows:rows.length,balance:'Equal counts in10 score bins per split; cutpoints estimated from training pool only',trainingScoreBinUpperBounds:boundaries,selection:'SHA256 seeded deterministic identity ranking inside each predeclared split/bin',splitMethod:'Released DOCKSTRING structure-cluster train/test; validation held-out by whole training clusters using seeded hash modulo5',scaffoldSplit:false,identityDedup:'One representative per InChIKey connectivity layer (first14characters), plus unique full InChIKey and source SMILES',testCaveat:'Outcome-stratified test subset: ranking/association metrics apply to this balanced benchmark, not prevalence-calibrated population performance'},compounds:selected.map(({scoreBin,...r})=>r)};
fs.writeFileSync(path.join(out,'dataset.json'),JSON.stringify(data));fs.writeFileSync(path.join(out,'subset-source.tsv'),['inchikey\tsmiles\tPARP1\tcluster\toriginal_split\tfinal_split\tscore_bin\tsource_row',...selected.map(r=>[r.id,r.smiles,r.score,r.cluster,r.originalSplit,r.split,r.scoreBin,r.sourceRow].join('\t'))].join('\n')+'\n');
const stats=Object.fromEntries(Object.keys(counts).map(split=>{const a=selected.filter(r=>r.split===split);return [split,{n:a.length,clusters:new Set(a.map(r=>r.cluster)).size,min:Math.min(...a.map(r=>r.score)),max:Math.max(...a.map(r=>r.score)),mean:a.reduce((s,r)=>s+r.score,0)/a.length,bins:Array.from({length:10},(_,i)=>a.filter(r=>r.scoreBin===i).length)}]}));const audit={datasetSha256:digest(fs.readFileSync(path.join(out,'dataset.json'))),sourceSubsetSha256:digest(fs.readFileSync(path.join(out,'subset-source.tsv'))),clusterOverlapAcrossSplits:0,duplicateConnectivity:0,duplicateInchiKey:0,sourceIdentityScoreJoinVerified:true,stats};fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify(audit,null,2));console.log(JSON.stringify(audit,null,2));
