import {PrincipleInfographic} from './components/PrincipleInfographic';
import {LangContext,useLang,useLangState} from './lib/i18n';
import {CNS} from './lib/cnsDataset.ts';
import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {FlyWireBrainScene} from './components/FlyWireBrainScene';
import {ColonyHabitat} from './components/ColonyHabitat';
import {MolecularStudio} from './components/MolecularStudio';
import {EvidencePanel} from './components/EvidencePanel';
import {AssayTrace} from './components/AssayFly';
import {BrainGrid} from './components/BrainGrid';
import {REGIONS,REGION_CSS,regionRates} from './components/brainRegions';
import {useContinuousColony} from './lib/useContinuousColony';
import {FLY_COUNT_OPTIONS,FLY_COUNT_STORAGE_KEY,flyCountForDevice,normalizeFlyCount,type HabitatPair,type ColonyFly} from './lib/colonyPolicy';
/** Public static build (drug.flybrain.kr): no local assay server. Detected at runtime by probing /api/docking/status. */
const PUBLIC_STORAGE_CAP_BYTES=500*1024*1024;
function initialFlyCount(){try{const stored=normalizeFlyCount(localStorage.getItem(FLY_COUNT_STORAGE_KEY));if(stored)return stored;}catch{/* storage optional */}return flyCountForDevice(typeof navigator==='undefined'?undefined:navigator.hardwareConcurrency);}
import './style.css';
import './habitat.css';
const names=['ION','EMBER','ULTRA','LIME','COBALT','AMBER','VIOLA','MOSS','CORAL','SLATE','OCHRE','TEAL','ROSE','PINE','FLAX','INDIGO','RUST','SAGE','PEARL','ONYX'];
const flyLabel=(i:number)=>String(i+1).padStart(2,'0');

const locations:[number,number,number][]=[[-6,1,-3.6],[-2,2,-3.8],[2,.5,-3.4],[6,1.6,-3.8],[-6,-.6,3.6],[-2,.6,3.8],[2,1.5,3.4],[6,0,3.6]];
function BrainPanel({fly,index,pairs,large=false}:{fly?:ColonyFly;index:number;pairs:HabitatPair[];large?:boolean}){const f=fly?.frame,total=fly?.dwell.reduce((a,b)=>a+b,0)||1;return <article className={'live-brain i'+index+(large?' large':'')}><div className="live-brain-head"><strong><i/> {names[index]??'FLY'} <em>{flyLabel(index)}</em></strong><span>{f?'STEP '+f.tick:'INITIALIZING'}</span></div><div className="live-brain-canvas"><FlyWireBrainScene frame={f} compact={!large} tone={index%4}/></div><div className="live-spike"><b>{f?.spikeCount.toLocaleString()??'—'}</b><span>spikes / computed step</span></div><AssayTrace frame={f} tone={index%4}/><div className="live-feed"><span>LEARNED APPETITE</span><b>{((fly?.feeding??0)*100).toFixed(0)}%</b></div><div className="appetite-track"><i style={{width:((fly?.feeding??0)*100)+'%'}}/></div><div className="destination"><small>APPROACHING</small><span>{pairs[fly?.destination??0]?.name??'Loading'} <em>· {pairs[fly?.destination??0]?.targetName}</em></span></div><div className="residence" title="Measured near-complex residence, not docking scores">{pairs.map((p,j)=><i key={p.id} title={p.targetName+' / '+p.name+': '+((fly?.dwell[j]??0)/total*100).toFixed(1)+'%'} style={{width:((fly?.dwell[j]??0)/total*100)+'%',background:['#45cbd0','#efa773','#bc9adb','#a7ce79','#7695ce','#d28b9c'][j%6]}}/>)}</div></article>}
/** Real per-step values of the selected fly: sensory input channels, decoded motor output, learned preferences and region spike rates. Nothing here is animated; every number comes from the latest computed frame. */
function SelectedFlyDetail({fly,index,pairs,manifest}:{fly?:ColonyFly;index:number;pairs:HabitatPair[];manifest:{groups:string[];classes:Record<string,number>}|null}){const f=fly?.frame;const rates=regionRates(f?.groupSpikeCounts,manifest?.groups??[],manifest?.classes??{});return <article className={'fly-detail i'+index}><div className="live-brain-head"><strong><i/> {names[index]??'FLY'} <em>{flyLabel(index)}</em> · DETAIL</strong><span>{f?'STEP '+f.tick:'INITIALIZING'}</span></div>
<div className="detail-block"><small>REGION SPIKE RATE · this step</small>{REGIONS.map((r,k)=><div key={r.id} className="detail-row"><span>{r.label}</span><i style={{background:REGION_CSS[k],width:Math.min(100,rates[k]/.12*100)+'%'}}/><b>{(rates[k]*100).toFixed(2)}%</b></div>)}</div>
<div className="detail-block"><small>SENSORY INPUT · {f?.sensory.length??0} channels</small><div className="detail-bars">{(f?.sensory??[]).map((v,k)=><i key={k} title={'channel '+k+': '+v.toFixed(3)} style={{height:(Math.max(0,Math.min(1,v))*100)+'%'}}/>)}</div></div>
<div className="detail-block"><small>DECODED MOTOR OUTPUT · turn / lift / thrust</small><div className="detail-bars motor">{(f?.output??[0,0,0]).map((v,k)=><i key={k} title={['turn','lift','thrust'][k]+': '+v.toFixed(3)} style={{height:(Math.abs(v)*100)+'%',opacity:v<0?.55:1}}/>)}</div></div>
<div className="detail-block"><small>LEARNED PREFERENCE · per executed pair</small>{pairs.map((p,j)=><div key={p.id} className={'detail-row'+(fly?.destination===j?' current':'')}><span>{String(j+1).padStart(2,'0')} {p.name}</span><i style={{background:['#45cbd0','#efa773','#bc9adb','#a7ce79','#7695ce','#d28b9c'][j%6],width:((fly?.learned[j]??0)*100)+'%'}}/><b>{((fly?.learned[j]??0)*100).toFixed(0)}%</b></div>)}</div>
</article>}
function App(){const {lang,t,setLang}=useLang();const [pairs,setPairs]=useState<HabitatPair[]>([]),[loadError,setLoadError]=useState(''),[selected,setSelected]=useState(0),[selectedFly,setSelectedFly]=useState(0),[detail,setDetail]=useState(false),[methods,setMethods]=useState(false),[provenance,setProvenance]=useState<any>(null),[followFly,setFollowFly]=useState(false),[manifest,setManifest]=useState<{groups:string[];classes:Record<string,number>}|null>(null),[flyCount,setFlyCountState]=useState(initialFlyCount),[publicMode,setPublicMode]=useState<boolean|null>(null);
// Until the probe answers, assume the public (no server) mode so the storage cap is never bypassed by a race.
const colony=useContinuousColony(pairs,{flyCount,storageCapBytes:publicMode===false?Infinity:PUBLIC_STORAGE_CAP_BYTES});
const setFlyCount=(n:number)=>{setFlyCountState(n);try{localStorage.setItem(FLY_COUNT_STORAGE_KEY,String(n));}catch{/* storage optional */}};
useEffect(()=>{let disposed=false;(async()=>{let local=false;try{const r=await fetch('/api/docking/status',{cache:'no-store'});if(r.ok&&(r.headers.get('content-type')||'').includes('application/json')){const j=await r.json();local=typeof j?.status==='string';}}catch{local=false;}if(!disposed)setPublicMode(!local);})();return()=>{disposed=true;};},[]);
useEffect(()=>{let disposed=false;fetch('/data/malecns/manifest.json').then(r=>r.json()).then(m=>{if(!disposed)setManifest({groups:m.groups,classes:m.classes});}).catch(()=>{});return()=>{disposed=true;};},[]);
useEffect(()=>{let disposed=false;void Promise.all([fetch('/data/docking/multi-target.json'),fetch('/data/docking/structure-scale.json').then(async r=>{if(!r.ok)throw Error('Measured structure dimensions unavailable');return r.json();})]).then(([r,scale])=>{(r as any).structureScale=scale;return r;}).then(async r=>{if(!r.ok)throw Error('Multi-target docking results not yet available. No synthetic complexes substituted.');const data=await r.json();data.structureScale=(r as any).structureScale;return data;}).then(d=>{if(disposed)return;const list=d.combinations.map((c:any,i:number)=>{const t=d.targets.find((t:any)=>t.id===c.targetId);const measured=d.structureScale.targets.find((x:any)=>x.targetId===c.targetId);if(!measured||!Number.isFinite(measured.radiusWorld))throw Error('Measured target radius missing');if(!t||c.computed!==true||!Number.isFinite(c.score))throw Error('Unexecuted molecular combination');return {id:c.id,targetId:c.targetId,targetName:t.name,compoundId:c.compoundId,name:c.name,smiles:c.smiles,score:c.score,poseUrl:c.poseUrl,receptorUrl:t.displayReceptorPdbqt??t.receptorPdbqt??t.receptorPdb??t.receptorUrl,position:locations[i%locations.length],radiusWorld:measured.radiusWorld,computed:true} as HabitatPair;});setPairs(list);setProvenance(d);}).catch(e=>setLoadError(String(e)));return()=>{disposed=true;};},[]);
const pick=pairs[selected],targetCount=new Set(pairs.map(p=>p.targetId)).size;
// One large point-cloud panel for the selected fly; all brains are drawn live in the shared-canvas grid below.
return <div className="habitat-app"><header><a className="brand" href="/"><b>FDDD</b><span>FLY-DRIVEN DRUG DEVELOPMENT</span></a><div className="header-tag">A LIVING MOLECULAR HABITAT</div><div className="header-actions"><div className="lang-toggle" role="group" aria-label="Language"><button className={lang==='ko'?'on':''} aria-pressed={lang==='ko'} onClick={()=>setLang('ko')}>{t('langKo')}</button><button className={lang==='en'?'on':''} aria-pressed={lang==='en'} onClick={()=>setLang('en')}>{t('langEn')}</button></div><button onClick={()=>setMethods(v=>!v)}>Methods & sources ↗</button></div></header><main><section className="habitat-title"><div><span className="eyebrow">CONTINUOUS CONNECTOME / MOLECULAR PREFERENCE</span><h1>A space to explore. A preference to learn.</h1></div><div className="habitat-controls"><span className={'live-tag '+(colony.ready&&!colony.paused?'on':'')}>{!colony.ready?'LOADING':colony.paused?'PAUSED':'LIVE · '+colony.flyCount+' BRAINS'}</span><label className="fly-count-select" title="Colony size. Every fly runs its own full 167,122-neuron MaleCNS worker; changing this restarts the colony session. Default is chosen from this device's CPU cores."><span>BRAINS</span><select value={flyCount} disabled={colony.exporting} onChange={e=>setFlyCount(Number(e.target.value))}>{FLY_COUNT_OPTIONS.map(n=><option key={n} value={n}>{n}</option>)}</select></label><button disabled={!colony.ready||colony.exporting} onClick={colony.paused?colony.resume:colony.pause}>{colony.paused?'Resume colony':'Pause colony'}</button><button className={colony.training?'reward-enabled':''} onClick={()=>colony.setTraining(!colony.training)}>{colony.training?'Reward ON · learning':'Reward OFF · frozen'}</button></div></section>
{(loadError||colony.error)&&<p className="error" role="alert">{loadError||colony.error}</p>}
<div className="habitat-meta"><span><b>{targetCount}</b> proteins · <b>{pairs.length}</b> executed combinations</span><span><b>{colony.flyCount} × {CNS.neuronCount.toLocaleString()}</b> neurons · MaleCNS brain + VNC</span><span><b>{colony.steps.toLocaleString()}</b> complete brain steps recorded</span><span className="record-indicator">ALL-CELL SPIKES · {(colony.bytes/1048576).toFixed(1)} MB raw</span></div>{publicMode&&<div className="build-note">Public build · {location.host} · all brain steps are computed in your browser; nothing is uploaded. Recorded spike frames stay in this browser's IndexedDB (cap {PUBLIC_STORAGE_CAP_BYTES/1048576} MB). Earlier sessions are deleted automatically when a new session starts.</div>}{!publicMode&&<div className="build-note">Local build · full-population spike frames are stored in this browser only for the live session; earlier sessions are deleted automatically when a new session starts. Use “Save CNS records to project” before reloading if you want to keep them.</div>}{colony.recordingCapped&&<div className="build-note warn" role="status">Recording paused at {PUBLIC_STORAGE_CAP_BYTES/1048576} MB cap (browser storage); computation continues. {colony.droppedSteps.toLocaleString()} computed steps since the cap are no longer stored.</div>}
<div className="cns-scope"><b>MaleCNS v1.0</b><span>{CNS.edgeCount.toLocaleString()} directed connections per fly · ≥5 synapses / connection</span><span>Brain + ventral nerve cord · selected annotated population</span></div>
<PrincipleInfographic/><div className="habitat-layout"><aside className="brain-column single" aria-label="Selected fly neural activity"><BrainPanel index={selectedFly} fly={colony.flies[selectedFly]} pairs={pairs} large/></aside><section className="shared-habitat"><div className="world-toolbar"><span>SHARED 3D MOLECULAR SPACE</span><small>Drag rotate · scroll zoom · right-drag pan</small><button className={'follow-toggle'+(followFly?' on':'')} aria-pressed={followFly} onClick={()=>setFollowFly(v=>!v)}>{followFly?'Following '+(names[selectedFly]??'FLY')+' '+flyLabel(selectedFly)+' · stop':'Follow selected fly'}</button></div><ColonyHabitat pairs={pairs} flies={colony.flies} paused={colony.paused} selected={selectedFly} onSelect={setSelectedFly} follow={followFly}/><div className="world-foot"><span>Real receptor coordinates + executed Vina poses</span><span>Continuous flight · learned residence preference</span></div>{!pairs.length&&<div className="world-loading">Loading executed molecular complexes…</div>}</section><aside className="brain-column single" aria-label="Selected fly computed detail"><SelectedFlyDetail index={selectedFly} fly={colony.flies[selectedFly]} pairs={pairs} manifest={manifest}/></aside></div>
<BrainGrid flies={colony.flies} pairs={pairs} selected={selectedFly} onSelect={setSelectedFly} names={names} count={colony.flyCount}/>
<div className="habitat-legend"><span>{REGIONS.map((r,k)=><i key={r.id} className="region-dot" style={{background:REGION_CSS[k]}} title={r.label}/>)}region palette (official superclass) · brightness = membrane activity · flash = actual spike</span><span>{CNS.displayCount.toLocaleString()} measured soma samples / {CNS.neuronCount.toLocaleString()} CNS neurons per fly · no fabricated activity waves</span></div>
<section className="combination-strip" aria-label="Executed protein molecule combinations">{pairs.map((p,i)=>{const recent=colony.recentResidence,dwell=recent[i]??0,all=recent.reduce((x:number,y:number)=>x+y,0)||1;return <button key={p.id} title={p.targetName+' / '+p.name} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><small>{String(i+1).padStart(2,'0')} / {p.targetName}</small><strong>{p.name}</strong><div><b>{p.score.toFixed(2)}</b><span>Vina kcal/mol</span></div><div className="occupancy"><i style={{width:dwell/all*100+'%'}}/></div><em>{(dwell/all*100).toFixed(1)}% residence · last 3 min</em></button>})}</section>
<div className="habitat-actions"><p>{t('actionsNote')}<strong>{t('actionsWarn')}</strong></p><button disabled={!pick} onClick={()=>setDetail(true)}>Selected complex in Mol* ↗</button>{publicMode?<button disabled title="The record-save endpoint exists only in the local project server. Nothing is uploaded from the public build.">Project save available only in the local build (records stay in this browser's IndexedDB)</button>:<button disabled={!colony.steps||colony.exporting||publicMode===null} onClick={()=>void colony.exportRecords()}>{colony.exporting?'Saving to project…':'Save CNS records to project'}</button>}</div>
{colony.exportStatus!=='idle'&&<output className="record-save-status" role="status">{colony.exportStatus==='saving'?'Saving CNS records inside project · '+colony.savedSegments+' segments confirmed':colony.exportStatus==='saved'?'Saved '+colony.savedSegments+' segments · '+colony.savedPath:'Project save failed. IndexedDB recordings are retained.'}</output>}
{methods&&<section className="methods"><h2>What is real, what is modeled</h2><p>{colony.flyCount} independent MaleCNS v1.0 brain + VNC circuits run continuously, one worker per fly. Every computed step records all {CNS.neuronCount.toLocaleString()} spike flags. Neural output influences motion; spatial steering, flight mechanics, food response and the reward-learning adapter are engineered, not experimentally validated fly physiology. The colored brain point cloud amplifies actual activity; rotation is a viewing aid.</p><p>Multiple experimental receptor structures and calculated AutoDock Vina poses occupy one shared coordinate scene. Every complex uses the same 0.03 world units per Angstrom. Only its scene translation differs; receptor/ligand coordinates and relative protein sizes are preserved. The orthographic 3D camera avoids perspective size distortion. Fly avatars are not on the molecular physical scale. Proximity uses each structure’s measured bounding radius plus an authored margin, not atom-level surface contact. These are crystal structures, not AlphaFold predictions. Raw cross-target Vina scores are not calibrated affinities or clinical efficacy. Learning preferences over rewarded candidates does not independently discover binding strength, and it is separate from the earlier PARP1 held-out benchmark.</p><p>Current runtime is the connected male brain plus VNC. <a href="https://www.janelia.org/project-team/flyem/male-cns-connectome">MaleCNS v1.0</a> publicly provides a connected male brain and ventral nerve cord from one specimen. The runtime uses its own v1.0 neuron IDs, connectivity, neurotransmitter predictions and measured soma coordinates. No female FAFB neurons are appended. Edges with fewer than five synapses are excluded; dynamics and sensory/motor decoding remain authored models.</p><p>Population: 165,122 Traced-status neurons plus 2,000 additional annotated, null-status neurons. Of those additions, 1,991 are explicitly labeled Out of scope in the source, not fully traced neurons. This is an expanded, thresholded MaleCNS-derived model, not every source segment or the exact official neuPrint neuron population. The selected population has 25,578,815 directed neuron pairs before filtering; 6,241,236 pairs with at least five synapses are retained, representing 89,851,287 synapses.</p><p><a href="/data/docking/multi-target.json">Executed combinations, protocols and sources ↗</a> · <a href="/data/malecns/NOTICE.md">Current engine data notice ↗</a></p>{provenance?.notes&&<p>{Array.isArray(provenance.notes)?provenance.notes.join(' '):provenance.notes}</p>}</section>}
<EvidencePanel/><footer><span>MaleCNS v1.0 runtime · CC BY 4.0 connectivity · research demonstration · no measured-affinity claim</span><span>MaleCNS CC BY 4.0 · AutoDock Vina / Webina · Mol* MIT · DOCKSTRING · BindingDB · DailyMed — <a href="/THIRD_PARTY_NOTICES.txt">see /THIRD_PARTY_NOTICES</a></span><span>Built with <a href="https://github.com/cobanov/fly-connectome-template">fly-connectome-template</a> by <a href="https://github.com/cobanov">Mert Cobanov</a>.</span></footer></main>
{detail&&pick&&<div className="structure-modal" role="dialog" aria-modal="true" aria-label="Professional structure detail"><div><div className="panel-head"><strong>{pick.targetName} / {pick.name}</strong><button onClick={()=>setDetail(false)}>Close structure detail</button></div><MolecularStudio receptorPath={pick.receptorUrl} posePath={pick.poseUrl} name={pick.targetName+' / '+pick.name}/><p className="fine-note">Detailed Mol* inspection. The colony and all {colony.flyCount} brain computations continue behind this view.</p></div></div>}
</div>}
function Root(){const state=useLangState();return <LangContext.Provider value={state}><App/></LangContext.Provider>;}
createRoot(document.getElementById('root')!).render(<Root/>);
