import {prismVariants,makePrismVariant} from './prism-models';
import {flightPose} from './flightPose';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {candidates,makeCandidate,disposeTree} from './models';
import {makeEnvironment,type SpaceMode} from './environment';
type Props={prismOnly:boolean;flying:boolean;resting:boolean;selected:number;overview:boolean;paused:boolean;space:SpaceMode;reset:number;onSelect:(index:number)=>void};
function marker(text:string){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.textAlign='center';ctx.font='20px monospace';ctx.fillStyle='#91afb8';ctx.fillText(text,128,40);const tex=new T.CanvasTexture(canvas);tex.colorSpace=T.SRGBColorSpace;const sprite=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));sprite.scale.set(2.6,.65,1);sprite.position.set(0,-.87,0);return sprite;}
export function Stage(props:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(props),actions=useRef<{fit:()=>void;update:()=>void}|undefined>(undefined),[error,setError]=useState('');latest.current=props;
 useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false});}catch{setError('WebGL을 사용할 수 없습니다. 이 페이지에는 실제 Three.js 렌더러가 필요합니다.');return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x070e13);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.domElement.setAttribute('aria-label',latest.current.prismOnly?'Three PRISM optimization levels in flight. Drag to rotate, scroll to zoom.':'Six Three.js fly designs. Drag to rotate, scroll to zoom. Click a fly to select.');renderer.domElement.style.touchAction='none';el.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.fog=new T.FogExp2(0x070e13,.019);scene.add(new T.HemisphereLight(0xd9edf2,0x202d36,2.4));const key=new T.DirectionalLight(0xf4eee3,4.2);key.position.set(4,8,5);scene.add(key);const rim=new T.DirectionalLight(0x83bed3,3.5);rim.position.set(-7,4,-4);scene.add(rim);const fill=new T.DirectionalLight(0xbfc0e4,1.8);fill.position.set(6,1,-2);scene.add(fill);
 const camera=new T.PerspectiveCamera(38,1,.05,160),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=2.8;controls.maxDistance=40;controls.maxPolarAngle=Math.PI*.88;
 const specs=latest.current.prismOnly?prismVariants:candidates;const models=specs.map((_,i)=>latest.current.prismOnly?makePrismVariant(i as 0|1|2|3|4):makeCandidate(i));models.forEach((m,i)=>{m.root.userData.candidate=i;m.wings.forEach(w=>{w.userData.openYaw=w.rotation.y;w.userData.hingeY=w.position.y;});m.root.add(marker(specs[i].number+' / '+specs[i].name));scene.add(m.root);});
 const positions=latest.current.prismOnly?[[-4.4,0,-1.6],[0,0,-1.6],[4.4,0,-1.6],[-2.2,0,1.9],[2.2,0,1.9]]:[[-4,0,-2.7],[0,0,-2.7],[4,0,-2.7],[-4,0,2.7],[0,0,2.7],[4,0,2.7]];
 const trails=models.map((_,i)=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(new Float32Array(48*3),3));const line=new T.Line(g,new T.LineBasicMaterial({color:specs[i].accent,transparent:true,opacity:.24,depthWrite:false}));line.frustumCulled=false;scene.add(line);return line;});
 let environment:T.Group,previousSpace:SpaceMode|undefined,previousOverview:boolean|undefined,previousSelection=-1,time=0,raf=0,last=0;
 const fit=()=>{const p=latest.current;controls.target.set(0,0,0);const aspect=Math.max(.65,camera.aspect);if(p.overview){if(p.prismOnly)camera.position.set(.8,6.5,12).multiplyScalar(.85*Math.max(1,1.35/aspect));else camera.position.set(1.3,10,14).multiplyScalar(.78*Math.max(1,1.35/aspect));}else camera.position.set(3.2,2.7,4.8).multiplyScalar(Math.max(1,1/aspect));controls.update();};
 const update=()=>{const p=latest.current;if(p.space!==previousSpace){if(environment){scene.remove(environment);disposeTree(environment);}environment=makeEnvironment(p.space);scene.add(environment);previousSpace=p.space;}models.forEach((m,i)=>{m.root.visible=p.overview||i===p.selected;m.root.position.fromArray(p.overview?positions[i]:[0,0,0]);m.root.scale.setScalar(1);const label=m.root.children.at(-1)!;label.visible=p.overview;});if(p.overview!==previousOverview){fit();previousOverview=p.overview;}previousSelection=p.selected;};actions.current={fit,update};
 const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/Math.max(1,el.clientHeight);camera.updateProjectionMatrix();fit();};const observer=new ResizeObserver(resize);observer.observe(el);resize();update();
 const ray=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0];const onDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const onUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(models.filter(m=>m.root.visible).map(m=>m.root),true)[0];if(hit){let obj:T.Object3D|null=hit.object;while(obj&&obj.userData.candidate===undefined)obj=obj.parent;if(obj)latest.current.onSelect(obj.userData.candidate);}};renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);
 const animate=(now:number)=>{const dt=Math.min(.05,(now-last)/1000||0);last=now;const p=latest.current;if(!p.paused)time+=dt;if(p.space!==previousSpace||p.overview!==previousOverview||p.selected!==previousSelection)update();models.forEach((m,i)=>{trails[i].visible=m.root.visible&&p.flying;if(!m.root.visible)return;const base=p.overview?positions[i]:[0,0,0];if(p.flying){const a=trails[i].geometry.getAttribute('position') as T.BufferAttribute;for(let j=0;j<48;j++){const trailPose=flightPose(Math.max(0,time-(47-j)*.05));a.setXYZ(j,base[0]+trailPose.position[0],base[1]+trailPose.position[1],base[2]+trailPose.position[2]);}a.needsUpdate=true;}const pose=flightPose(time);if(p.flying){m.root.position.set(base[0]+pose.position[0],base[1]+pose.position[1],base[2]+pose.position[2]);m.root.rotation.set(pose.pitch,pose.yaw,pose.roll);}else{m.root.position.set(base[0],base[1]+Math.sin(time*1.3+i*.8)*.025,base[2]);m.root.rotation.set(0,0,0);}m.wings.forEach((wing,j)=>{const side=j===0?-1:1;wing.position.y=(wing.userData.hingeY??.235)+(p.resting?.105+(j===0?.007:0):0);wing.rotation.y=p.resting?side*1.12:(wing.userData.openYaw??0);wing.rotation.z=side*(p.resting?.018+Math.sin(time*4+i)*.006:.07+Math.sin(time*(p.flying?48:13)+(p.flying?0:i))*(p.flying?.55:.14));});});controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(animate);};raf=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(raf);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onUp);disposeTree(scene);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();actions.current=undefined;};},[props.prismOnly]);
 useEffect(()=>{actions.current?.fit();},[props.reset]);
 return <div className="stage-host" ref={host}>{error&&<p role="alert" className="stage-error">{error}</p>}</div>;
}
